# Default values for k8s-sizing-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/bitteeinbit/k8s-sizing-webhook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65535

webhook:
  debug: true
  tls:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuRENDQXdTZ0F3SUJBZ0lRWlVCdlltdTFDU1RqZFNTejFFRFJjREFOQmdrcWhraUc5dzBCQVFzRkFEQ0IKcVRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNVDh3UFFZRFZRUUxERFpxYjI1aApkR2hoYmk1MmIyZDBRRVJGTFVKRlVpMU5RVU13TURBekxtWnlhWFI2TG1KdmVDQW9TbTl1WVhSb1lXNGdWbTluCmRDa3hSakJFQmdOVkJBTU1QVzFyWTJWeWRDQnFiMjVoZEdoaGJpNTJiMmQwUUVSRkxVSkZVaTFOUVVNd01EQXoKTG1aeWFYUjZMbUp2ZUNBb1NtOXVZWFJvWVc0Z1ZtOW5kQ2t3SGhjTk1qSXdOakl3TURjek56QXhXaGNOTWpRdwpPVEl3TURjek56QXhXakJxTVNjd0pRWURWUVFLRXg1dGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1kyVnlkR2xtCmFXTmhkR1V4UHpBOUJnTlZCQXNNTm1wdmJtRjBhR0Z1TG5adlozUkFSRVV0UWtWU0xVMUJRekF3TURNdVpuSnAKZEhvdVltOTRJQ2hLYjI1aGRHaGhiaUJXYjJkMEtUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFNWVVIOHBKYzJkdjZDbW5VVUVMUGVMdDAzWjV2blAzQmRCcHJneTdoU1lBZWNmK2ptWWQ4NHBICkVjRFFGc3d0KzJPVGJuSCtoOHo0SlM1Y0g5djRzaE9rQ3BFVlhvekVhYWlDeVppTHRSeUZwa2czRlFnRGpqV0oKV3phYnpuY0ZreG91WForaHVCVXVNNGZ4Z1ZZbG9mZ1U0bEtDY01RVjd4blBBR2VOVFVkd045MlZaQ2N2bnFEbApvdS9ZTjI2QVZjR2huZlRodkl6ZTZVNWVobExPODRFZThteW8zNnMrT1ZncVlRZ0hZeW5Faml4clBLQ0VxMGpCClNDV3pxanB0R2hxMU5RK1dWYnhsa0dUQXkwL3VxQjRzTVlqbTI3S2pNWmhmMmRVUFNUa2JXRU9YOE9GWFRQUzkKYXk4M3RCWHcxMmhvQ3NOQXpMU2FIVTFTMC9Jd3M5a0NBd0VBQWFOK01Id3dEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUI4R0ExVWRJd1FZTUJhQUZIUmprSFJrMk5kZWdaVGZWSjMxCjFCMGhJUzRwTURRR0ExVWRFUVF0TUN1Q0tXczRjeTF6YVhwcGJtY3RkMlZpYUc5dmF5NXJPSE10YzJsNmFXNW4KTFhkbFltaHZiMnN1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlRsd0FkZGxTa29BSXM5aGpBRWxaaQp5eWduY3JDWmtpOGJCUWpyb3hKdTNqcHhCeEJ6RXpDSU14R3Rmc3RuVXpWL01zb2xucThhbDlvRk42Y1VZUVphCm5maUtuRGFMcC9WUWtUbzVlN3lxSHZFdDFnMHI5bUhoQzYrb3p5NllxUUIzYUkydm9kN3lFYzV3YXJub0U3RDQKckcvZ3JLL0l5bHRqYnhqQmlnSkJleUVTR29XcTRtQWZBSEdtb2JxT0MvTHR5ZHhNYjYxa0VnS3l5SUlFQVcrNAo2U1pvVVFPV2Z0aWdhcldUd1BRSFdIT0JBc2lBR1k3ekJWN2ZaNzJpV1hQQnIyeFA1Ulg3aE5JYnFXUWVGQ05DCjk1eWEvRldlZ0MxL3lZNGtSY0tUcHRXN3V4MVlpNGFUUjdiNUhCRHR3QWJkdTNxQmFnLzdjZXpzM2R1SHRhOHUKMnRhcTdEL0F0WHM5RFdsM1dYS3k0Snl4dTU1a1hsc2tYTjNHWEJvWEk5UFlGTFQxTlRJQURZdFhwU3d3K05HdQpOa2tWQ0pLQ3ArZFFnMlpHbnNIalpWaERHU2tzcUJSMk5oRzg0dEdaanhuVFdZWmhjS2tzNUkxeDMvVFBVaVVLCld1WHJTR24xTzZNNkkrVGxiZGhZZjVHZk5EcFc3MWdNY2JHc0FsMkZhWVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREdGQi9LU1hObmIrZ3AKcDFGQkN6M2k3ZE4yZWI1ejl3WFFhYTRNdTRVbUFIbkgvbzVtSGZPS1J4SEEwQmJNTGZ0amsyNXgvb2ZNK0NVdQpYQi9iK0xJVHBBcVJGVjZNeEdtb2dzbVlpN1VjaGFaSU54VUlBNDQxaVZzMm04NTNCWk1hTGwyZm9iZ1ZMak9ICjhZRldKYUg0Rk9KU2duREVGZThaendCbmpVMUhjRGZkbFdRbkw1Nmc1YUx2MkRkdWdGWEJvWjMwNGJ5TTN1bE8KWG9aU3p2T0JIdkpzcU4rclBqbFlLbUVJQjJNcHhJNHNhenlnaEt0SXdVZ2xzNm82YlJvYXRUVVBsbFc4WlpCawp3TXRQN3FnZUxER0k1dHV5b3pHWVg5blZEMGs1RzFoRGwvRGhWMHowdldzdk43UVY4TmRvYUFyRFFNeTBtaDFOClV0UHlNTFBaQWdNQkFBRUNnZ0VBQTkvczUwWWNqYzl3bVMvK3RPa0ZZdVVJRis4MXZJcitnQjh4R21xb3BoK28KUWpOR2tkVFFLTXBQSEpoMWViVUVqK1FZYXY1eHBaN05DMlVkOG0yZy9pVmRWNDAxZGtkNVVhU05VUUNhb0Y0MAo3SUMzVnByTE0xem1mZUQ2WHZXcTlQNG5NckkxS2FUbnVTY09RcU1sMGZhR250cVNYaU9YczhlSzJIdTVJVWFWCno2YlZEbFVHcVlnTHNFS0dyMThMTFo0cEQ0b05JcDZCbUVaSTNRTWJGMVJib2Fzbm1uZmJkcHZZOGtzRVFtRkYKZkhNdU9CcDd5aHZLcTNPY09kTHZreS9BWTNmN0tCUzJLZm44cmVwbSsxWDU2c3ljcXZCVWluSCtTaWxwNGV4dApMZXVmT0FoTFExZGhmL3JnL0tDNXBrRGhLdzhPRWpNaE0yQm1mMytMb1FLQmdRREdYTkNwdGs2a2ovbWk5bUJ3ClE5UmlYSWNmYU5CalNqelNncUNVZnVVaWdFcEtzSFo2WXBQdnNhb2kvcmlJREdCbDNDYmhrYVdoSlBveDhKakEKZEczdWVPRnljdmFWczFWUDZUYmtCSHdOVHNhR3pOQzUrMjJrVUxocTJKZUh1aDMwb3pqMWhMZjBobExLaDRKVwp4UG1pMnBNN0N0bFZPOFdTQi9YbUdhT1diUUtCZ1FEL29qQUU1RWczZFd4YStLQlRYajdQdCtnSmx3YzZ4aGwxCnNRSUN2ZlF0K0kzR0ZSbkhtd3RaaUVrM25raGJDUjNrMytqRDFtczk4TDIrNVN5TTFQRHB0ZTQwTUxmOHVtbXAKeDhvU2NsN2JLWGI5UUN5YWFycWw0dWVXR0JXQUlYbGY5bm5wZFhza2xkTisxZlhlMEFaVGdvc0sxeHlPeU4xegpOUkY0MlZkZm5RS0JnRHpHMDJnc1k0d29VT1NOZUo3dEtYVzV3K3pyd0cycm9WY2VqdlR3ckdRVnlxMTN3OVZiCnZ0Z0NKNDd4WExqU2tmYWpyWVlQaWlBRnBHTUl4TVN5NTd2WmJib1RYMW9leUZUanI5M05RZlVSM2VJUGZ5UjgKMU9zemtFMnNiMEUyMVZiUGEvUk41YzhXR09mVS9TcDR6OFFHRkhaU3JLUmcyL2dTV0ZWWUpiZEJBb0dCQVBNNwp5V0QrTFZESG8rQXpiYW1scFRKVUZLNzdTMSs3R29LSGVCaFAwY1RrR1ZIK3hkYk5TZEZaQWdHdjA3ejdRYnlDCjZLRmVwZy83dnkraU0rK1V0ZDVLdzJwWmFOZEtNRHZoNC80RllRZzd2Z0plUzVKcU4wcWNTaXJnbzZTVk5UMy8KOGlRWEtxSzNCTlJNbFhQNmorcHA3ZzdVZTFISkFoMGF3NU12aWhscEFvR0FNSlUxSlB3VDlmYWhlaXVvT1VEbAp0YUg4RFN2ellWOG1pTVdIVHBTVE01WGNyRTFDK2NDdmV5WDdtOUloaTNIb1VSK25Jek4rMEc2L21ZZ2FCRlNNCkgxUkpYSXpKbXZBRDl1MTNOSVNGSm80eHpFZVJFVzZEVDdMZ3VxM09UUDVRcXFCdGVXdEN5NGZiZytwN05OSWoKYWhZSDEyR1VmSWs3dkxxMitrTFM2NDg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVuRENDQXdTZ0F3SUJBZ0lRWlVCdlltdTFDU1RqZFNTejFFRFJjREFOQmdrcWhraUc5dzBCQVFzRkFEQ0IKcVRFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNVDh3UFFZRFZRUUxERFpxYjI1aApkR2hoYmk1MmIyZDBRRVJGTFVKRlVpMU5RVU13TURBekxtWnlhWFI2TG1KdmVDQW9TbTl1WVhSb1lXNGdWbTluCmRDa3hSakJFQmdOVkJBTU1QVzFyWTJWeWRDQnFiMjVoZEdoaGJpNTJiMmQwUUVSRkxVSkZVaTFOUVVNd01EQXoKTG1aeWFYUjZMbUp2ZUNBb1NtOXVZWFJvWVc0Z1ZtOW5kQ2t3SGhjTk1qSXdOakl3TURjek56QXhXaGNOTWpRdwpPVEl3TURjek56QXhXakJxTVNjd0pRWURWUVFLRXg1dGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1kyVnlkR2xtCmFXTmhkR1V4UHpBOUJnTlZCQXNNTm1wdmJtRjBhR0Z1TG5adlozUkFSRVV0UWtWU0xVMUJRekF3TURNdVpuSnAKZEhvdVltOTRJQ2hLYjI1aGRHaGhiaUJXYjJkMEtUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFNWVVIOHBKYzJkdjZDbW5VVUVMUGVMdDAzWjV2blAzQmRCcHJneTdoU1lBZWNmK2ptWWQ4NHBICkVjRFFGc3d0KzJPVGJuSCtoOHo0SlM1Y0g5djRzaE9rQ3BFVlhvekVhYWlDeVppTHRSeUZwa2czRlFnRGpqV0oKV3phYnpuY0ZreG91WForaHVCVXVNNGZ4Z1ZZbG9mZ1U0bEtDY01RVjd4blBBR2VOVFVkd045MlZaQ2N2bnFEbApvdS9ZTjI2QVZjR2huZlRodkl6ZTZVNWVobExPODRFZThteW8zNnMrT1ZncVlRZ0hZeW5Faml4clBLQ0VxMGpCClNDV3pxanB0R2hxMU5RK1dWYnhsa0dUQXkwL3VxQjRzTVlqbTI3S2pNWmhmMmRVUFNUa2JXRU9YOE9GWFRQUzkKYXk4M3RCWHcxMmhvQ3NOQXpMU2FIVTFTMC9Jd3M5a0NBd0VBQWFOK01Id3dEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUI4R0ExVWRJd1FZTUJhQUZIUmprSFJrMk5kZWdaVGZWSjMxCjFCMGhJUzRwTURRR0ExVWRFUVF0TUN1Q0tXczRjeTF6YVhwcGJtY3RkMlZpYUc5dmF5NXJPSE10YzJsNmFXNW4KTFhkbFltaHZiMnN1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlRsd0FkZGxTa29BSXM5aGpBRWxaaQp5eWduY3JDWmtpOGJCUWpyb3hKdTNqcHhCeEJ6RXpDSU14R3Rmc3RuVXpWL01zb2xucThhbDlvRk42Y1VZUVphCm5maUtuRGFMcC9WUWtUbzVlN3lxSHZFdDFnMHI5bUhoQzYrb3p5NllxUUIzYUkydm9kN3lFYzV3YXJub0U3RDQKckcvZ3JLL0l5bHRqYnhqQmlnSkJleUVTR29XcTRtQWZBSEdtb2JxT0MvTHR5ZHhNYjYxa0VnS3l5SUlFQVcrNAo2U1pvVVFPV2Z0aWdhcldUd1BRSFdIT0JBc2lBR1k3ekJWN2ZaNzJpV1hQQnIyeFA1Ulg3aE5JYnFXUWVGQ05DCjk1eWEvRldlZ0MxL3lZNGtSY0tUcHRXN3V4MVlpNGFUUjdiNUhCRHR3QWJkdTNxQmFnLzdjZXpzM2R1SHRhOHUKMnRhcTdEL0F0WHM5RFdsM1dYS3k0Snl4dTU1a1hsc2tYTjNHWEJvWEk5UFlGTFQxTlRJQURZdFhwU3d3K05HdQpOa2tWQ0pLQ3ArZFFnMlpHbnNIalpWaERHU2tzcUJSMk5oRzg0dEdaanhuVFdZWmhjS2tzNUkxeDMvVFBVaVVLCld1WHJTR24xTzZNNkkrVGxiZGhZZjVHZk5EcFc3MWdNY2JHc0FsMkZhWVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  mark:
    name: allmark.bitteeinbit.dev
    enable: true
    labels:
      kubewebhook: k8s-webhook-example
  memory:
    name: memfix.bitteeinbit.dev
    enable: true


serviceMonitor:
  create: false

podDisruptionBudget:
  create: true
  minAvailable: 1

topologySpreadConstraints:
  enable: true
  policy: ScheduleAnyway

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
