apiVersion: v1
metadata:
  name: {{ include "k8s-sizing-webhook.fullname" . }}
  labels:
    {{- include "k8s-sizing-webhook.labels" . | nindent 4 }}
data:
  "tls.crt": {{ .Values.webhook.tls.crt }}
  "tls.key": {{ .Values.webhook.tls.key }}
kind: Secret
type: kubernetes.io/tls
