apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-sizing-webhook.fullname" . }}
  labels:
    {{- include "k8s-sizing-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 443
      protocol: TCP
      name: http
    - targetPort: 8081
      port: 8081
      protocol: TCP
      name: metrics
  selector:
    {{- include "k8s-sizing-webhook.selectorLabels" . | nindent 4 }}
